"""
Migration script for users -> users
Generated by Migration Planner Agent
"""

import pymongo
import sqlalchemy
from sqlalchemy import create_engine, text
from pymongo import MongoClient
import json
from datetime import datetime

def migrate_users():
    """Migrate users table to users collection"""
    
    # Database connections
    sql_engine = create_engine('sqlite:///example.db')
    mongo_client = MongoClient('mongodb://localhost:27017/')
    db = mongo_client['migrated_db']
    collection = db['users']
    
    try:
        # Query SQL data
        with sql_engine.connect() as conn:
            query = text("SELECT * FROM users")
            result = conn.execute(query)
            rows = result.fetchall()
        
        # Transform and insert into MongoDB
        documents = []
        for row in rows:
            doc = {
                "username": row.username,
                "email": row.email,
                "first_name": row.first_name,
                "last_name": row.last_name,
                "created_at": row.created_at,
                "updated_at": row.updated_at
            }
            documents.append(doc)
        
        # Batch insert to MongoDB
        if documents:
            collection.insert_many(documents)
            print(f"Migrated {len(documents)} documents to users")
        
    except Exception as e:
        print(f"Error migrating users: {str(e)}")
        raise
    finally:
        sql_engine.dispose()
        mongo_client.close()

if __name__ == "__main__":
    migrate_users()