-- MongoDB setup script for users collection
-- Generated by Migration Planner Agent

use migrated_db;

-- Create collection
db.createCollection("users");

-- Create indexes
db.users.createIndex({"_id": 1});
db.users.createIndex({"username": 1});
db.users.createIndex({"email": 1});

-- Create validation rules
db.runCommand({
    collMod: "users",
    validator: {
        $jsonSchema: {
            bsonType: "object",
            required: ["username", "email", "first_name", "last_name", "created_at"]
        }
    }
});